name: ci
permissions: {}
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  build-tools:
    runs-on: ubuntu-latest
    name: Build Go Tools
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6.2.0
        with:
          go-version-file: scripts/go.mod
          cache-dependency-path: scripts/go.sum
      - name: Build Go tools
        run: |
          mkdir -p tmp/bin
          cd scripts && go list -e -mod=mod -tags tools -f '{{ range .Imports }}{{ printf "%s\n" .}}{{end}}' ./ | xargs -tI % go build -mod=mod -o ../tmp/bin %
      - name: Upload built tools
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: go-tools
          path: tmp/bin/
          retention-days: 1
          if-no-files-found: error

  matrix:
    runs-on: ubuntu-latest
    name: ${{ matrix.name }}
    needs: build-tools
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Lint Alerts
            run: make alerts-lint
          - name: Generate YAML
            run: make generate && git diff --exit-code
          - name: Lint Grafana Dashboards
            run: make dashboards-lint
          - name: Format JSONNET
            run: make jsonnet-fmt && git diff --exit-code
          - name: Lint JSONNET
            run: make jsonnet-lint
          - name: Format MD
            run: make markdownfmt && git diff --exit-code
          - name: Lint MD
            run: make vale && git diff --exit-code
          - name: Lint YAML
            run: make pint-lint
          - name: Run unit tests
            run: make test

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Download built tools
        uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7.0.0
        with:
          name: go-tools
          path: tmp/bin/
      - name: Make tools executable and update timestamps
        run: |
          chmod +x tmp/bin/*
          touch tmp/bin/*
      - run: ${{ matrix.run }}
