name: Release

on:
  push:
    tags:
      - "version-*" # Trigger the workflow on push events to version-* tags

permissions:
  contents: write

jobs:
  build:
    name: Build Artifact
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Set up Go
        uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6.2.0
        with:
          go-version-file: "scripts/go.mod"

      - name: Build release archive
        run: |
          echo "Building Grafana Dashboards, Prometheus Rules and Alerts"
          make
          echo "Compressing Artifacts"
          zip -r kubernetes-mixin-${{ github.ref_name }}.zip dashboards_out prometheus_alerts.yaml prometheus_rules.yaml

      - name: Upload artifact
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: kubernetes-mixin-${{ github.ref_name }}.zip
          path: ./

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7.0.0
        with:
          name: kubernetes-mixin-${{ github.ref_name }}.zip

      - name: Create release on kubernetes-mixin
        uses: softprops/action-gh-release@a06a81a03ee405af7f2048a818ed3f03bbf83c7b # v2.5.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          repository: kubernetes-monitoring/kubernetes-mixin
          generate_release_notes: true
          files: kubernetes-mixin-${{ github.ref_name }}.zip
